// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.21.11
// source: order.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PickUpReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      int64                  `protobuf:"varint,1,opt,name=DeviceId,proto3" json:"DeviceId,omitempty"`
	PickupCode    string                 `protobuf:"bytes,2,opt,name=PickupCode,proto3" json:"PickupCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PickUpReq) Reset() {
	*x = PickUpReq{}
	mi := &file_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PickUpReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PickUpReq) ProtoMessage() {}

func (x *PickUpReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PickUpReq.ProtoReflect.Descriptor instead.
func (*PickUpReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{0}
}

func (x *PickUpReq) GetDeviceId() int64 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

func (x *PickUpReq) GetPickupCode() string {
	if x != nil {
		return x.PickupCode
	}
	return ""
}

type PickUpResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OvertimeFee   float64                `protobuf:"fixed64,1,opt,name=overtime_fee,json=overtimeFee,proto3" json:"overtime_fee,omitempty"` // 超时费用
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PickUpResp) Reset() {
	*x = PickUpResp{}
	mi := &file_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PickUpResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PickUpResp) ProtoMessage() {}

func (x *PickUpResp) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PickUpResp.ProtoReflect.Descriptor instead.
func (*PickUpResp) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{1}
}

func (x *PickUpResp) GetOvertimeFee() float64 {
	if x != nil {
		return x.OvertimeFee
	}
	return 0
}

type CreateOrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      int64                  `protobuf:"varint,1,opt,name=DeviceId,proto3" json:"DeviceId,omitempty"`
	OrderCode     string                 `protobuf:"bytes,2,opt,name=OrderCode,proto3" json:"OrderCode,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=Phone,proto3" json:"Phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderReq) Reset() {
	*x = CreateOrderReq{}
	mi := &file_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderReq) ProtoMessage() {}

func (x *CreateOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderReq.ProtoReflect.Descriptor instead.
func (*CreateOrderReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{2}
}

func (x *CreateOrderReq) GetDeviceId() int64 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

func (x *CreateOrderReq) GetOrderCode() string {
	if x != nil {
		return x.OrderCode
	}
	return ""
}

func (x *CreateOrderReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type CreateOrderResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PickupCode    string                 `protobuf:"bytes,1,opt,name=PickupCode,proto3" json:"PickupCode,omitempty"`
	OrderCode     string                 `protobuf:"bytes,2,opt,name=OrderCode,proto3" json:"OrderCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderResp) Reset() {
	*x = CreateOrderResp{}
	mi := &file_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResp) ProtoMessage() {}

func (x *CreateOrderResp) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResp.ProtoReflect.Descriptor instead.
func (*CreateOrderResp) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{3}
}

func (x *CreateOrderResp) GetPickupCode() string {
	if x != nil {
		return x.PickupCode
	}
	return ""
}

func (x *CreateOrderResp) GetOrderCode() string {
	if x != nil {
		return x.OrderCode
	}
	return ""
}

type OrderListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderListReq) Reset() {
	*x = OrderListReq{}
	mi := &file_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderListReq) ProtoMessage() {}

func (x *OrderListReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderListReq.ProtoReflect.Descriptor instead.
func (*OrderListReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{4}
}

func (x *OrderListReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type OrderListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*OrderList           `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderListResp) Reset() {
	*x = OrderListResp{}
	mi := &file_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderListResp) ProtoMessage() {}

func (x *OrderListResp) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderListResp.ProtoReflect.Descriptor instead.
func (*OrderListResp) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{5}
}

func (x *OrderListResp) GetList() []*OrderList {
	if x != nil {
		return x.List
	}
	return nil
}

type OrderList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderList) Reset() {
	*x = OrderList{}
	mi := &file_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderList) ProtoMessage() {}

func (x *OrderList) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderList.ProtoReflect.Descriptor instead.
func (*OrderList) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{6}
}

type OrderDetailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderDetailReq) Reset() {
	*x = OrderDetailReq{}
	mi := &file_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderDetailReq) ProtoMessage() {}

func (x *OrderDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderDetailReq.ProtoReflect.Descriptor instead.
func (*OrderDetailReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{7}
}

type OrderDetailResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderDetailResp) Reset() {
	*x = OrderDetailResp{}
	mi := &file_order_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderDetailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderDetailResp) ProtoMessage() {}

func (x *OrderDetailResp) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderDetailResp.ProtoReflect.Descriptor instead.
func (*OrderDetailResp) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{8}
}

var File_order_proto protoreflect.FileDescriptor

const file_order_proto_rawDesc = "" +
	"\n" +
	"\vorder.proto\x12\x06stream\"G\n" +
	"\tPickUpReq\x12\x1a\n" +
	"\bDeviceId\x18\x01 \x01(\x03R\bDeviceId\x12\x1e\n" +
	"\n" +
	"PickupCode\x18\x02 \x01(\tR\n" +
	"PickupCode\"/\n" +
	"\n" +
	"PickUpResp\x12!\n" +
	"\fovertime_fee\x18\x01 \x01(\x01R\vovertimeFee\"`\n" +
	"\x0eCreateOrderReq\x12\x1a\n" +
	"\bDeviceId\x18\x01 \x01(\x03R\bDeviceId\x12\x1c\n" +
	"\tOrderCode\x18\x02 \x01(\tR\tOrderCode\x12\x14\n" +
	"\x05Phone\x18\x03 \x01(\tR\x05Phone\"O\n" +
	"\x0fCreateOrderResp\x12\x1e\n" +
	"\n" +
	"PickupCode\x18\x01 \x01(\tR\n" +
	"PickupCode\x12\x1c\n" +
	"\tOrderCode\x18\x02 \x01(\tR\tOrderCode\"&\n" +
	"\fOrderListReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\"6\n" +
	"\rOrderListResp\x12%\n" +
	"\x04list\x18\x01 \x03(\v2\x11.stream.OrderListR\x04list\"\v\n" +
	"\tOrderList\"\x10\n" +
	"\x0eOrderDetailReq\"\x11\n" +
	"\x0fOrderDetailResp2\xb2\x01\n" +
	"\x05Order\x12/\n" +
	"\x06PickUp\x12\x11.stream.PickUpReq\x1a\x12.stream.PickUpResp\x12>\n" +
	"\vCreateOrder\x12\x16.stream.CreateOrderReq\x1a\x17.stream.CreateOrderResp\x128\n" +
	"\tOrderList\x12\x14.stream.OrderListReq\x1a\x15.stream.OrderListRespB\x19Z\x17../../../internal/protob\x06proto3"

var (
	file_order_proto_rawDescOnce sync.Once
	file_order_proto_rawDescData []byte
)

func file_order_proto_rawDescGZIP() []byte {
	file_order_proto_rawDescOnce.Do(func() {
		file_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)))
	})
	return file_order_proto_rawDescData
}

var file_order_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_order_proto_goTypes = []any{
	(*PickUpReq)(nil),       // 0: stream.PickUpReq
	(*PickUpResp)(nil),      // 1: stream.PickUpResp
	(*CreateOrderReq)(nil),  // 2: stream.CreateOrderReq
	(*CreateOrderResp)(nil), // 3: stream.CreateOrderResp
	(*OrderListReq)(nil),    // 4: stream.OrderListReq
	(*OrderListResp)(nil),   // 5: stream.OrderListResp
	(*OrderList)(nil),       // 6: stream.OrderList
	(*OrderDetailReq)(nil),  // 7: stream.OrderDetailReq
	(*OrderDetailResp)(nil), // 8: stream.OrderDetailResp
}
var file_order_proto_depIdxs = []int32{
	6, // 0: stream.OrderListResp.list:type_name -> stream.OrderList
	0, // 1: stream.Order.PickUp:input_type -> stream.PickUpReq
	2, // 2: stream.Order.CreateOrder:input_type -> stream.CreateOrderReq
	4, // 3: stream.Order.OrderList:input_type -> stream.OrderListReq
	1, // 4: stream.Order.PickUp:output_type -> stream.PickUpResp
	3, // 5: stream.Order.CreateOrder:output_type -> stream.CreateOrderResp
	5, // 6: stream.Order.OrderList:output_type -> stream.OrderListResp
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_order_proto_init() }
func file_order_proto_init() {
	if File_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_proto_goTypes,
		DependencyIndexes: file_order_proto_depIdxs,
		MessageInfos:      file_order_proto_msgTypes,
	}.Build()
	File_order_proto = out.File
	file_order_proto_goTypes = nil
	file_order_proto_depIdxs = nil
}
